package web

import "github.com/flipped-aurora/gin-vue-admin/server/service"

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	ArticleApi
	ActivityApi
	ActivityRecordApi
	CommentApi
	IntroduceApi
	MessageApi
	MomentsApi
	OrganizationInformationApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.

	WebHomePageApi
	WebUserApi
}

var (
	userService = service.ServiceGroupApp.SystemServiceGroup.UserService
)
