package web

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	ArticleRouter
	ActivityRouter
	ActivityRecordRouter
	CommentRouter
	IntroduceRouter
	MessageRouter
	MomentsRouter
	OrganizationInformationRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.

	HomePageRouter
	WebUserRouter
}
