package web


type ServiceGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	ArticleService
	ActivityService
	ActivityRecordService
	CommentService
	IntroduceService
	MessageService
	MomentsService
	OrganizationInformationService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

